# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [2]:
import sys
import numpy as np

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [7]:
arr = [0] * 1000
sys.getsizeof(arr)

8056

In [9]:
sys.getsizeof(np.array(arr, dtype=np.int8))

1112

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [26]:
f = np.array([1.5, 3.2, 4.8, 6.1, 7.3, 9.9])
f[[0, 2, -1]]


array([1.5, 4.8, 9.9])

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [4]:
from itertools import combinations


array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
el = array[[0, 1, 4, 7]]
r_sum = np.sum(el)
r_sum

[ 2.3  7.8  5.8 11.1]


np.float64(27.0)

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [37]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [42]:
np.mean(A, axis=0)

array([2. , 8.4])

### Task 5.2 Get the standard deviation by `y` axis

In [41]:
np.std(A, axis=1)

array([2.5, 3. , 4. , 3.5, 3. ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [44]:
np.sum(A, axis=1)

array([ 7, 10, 14, 13,  8])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [47]:
A[:2, :]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [50]:
A[::2, :]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [60]:
# Python code
import time
start_time = time.time()
python_list = [i for i in range(1000000)]
end_time = time.time()
end_time - start_time

0.14699792861938477

In [70]:
import time
start_time = time.time()
numpy_array = np.arange(1000000)
end_time = time.time()
end_time - start_time

0.003002166748046875

### Task 6.2

In [84]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

start_time = time.perf_counter()

result = unknown_signature(vector1, vector2)

end_time = time.perf_counter()
execution_time_python = end_time - start_time

print("Result:", result)
print(f"Execution time: {execution_time_python:.10f} seconds")

Result: 32
Execution time: 0.0000617000 seconds


In [85]:
def unknown_signature_numpy(vector1, vector2):
    return np.dot(vector1, vector2)

vector1_np = np.array([1, 2, 3])
vector2_np = np.array([4, 5, 6])
result = 0

start_time_np = time.perf_counter()

result_np = unknown_signature_numpy(vector1_np, vector2_np)

end_time_np = time.perf_counter()
execution_time_numpy = end_time_np - start_time_np

print("Result:", result_np)
print(f"Execution time: {execution_time_numpy:.10f} seconds")

Result: 32
Execution time: 0.0001379000 seconds


### Task 6.3

In [92]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

start_time = time.perf_counter()

result = unknown_signature(matrix1, matrix2)

end_time = time.perf_counter()
execution_time_python = end_time - start_time

print("Result:", result)
print(f"Execution time: {execution_time_python:.10f} seconds")


Result: [[5, 12], [21, 32]]
Execution time: 0.0002390000 seconds


In [97]:
def unknown_signature_numpy(matrix1, matrix2):
    result = matrix1_np * matrix2_np
    return result.tolist()

matrix1_np = np.array([[1, 2], [3, 4]])
matrix2_np = np.array([[5, 6], [7, 8]])

start_time_np = time.perf_counter()

result_np = unknown_signature_numpy(matrix1_np, matrix2_np)

end_time_np = time.perf_counter()
execution_time_numpy = end_time_np - start_time_np

print("Result:", result_np)
print(f"Execution time: {execution_time_numpy:.10f} seconds")

Result: [[5, 12], [21, 32]]
Execution time: 0.0000951000 seconds


### Task 6.4

In [94]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

start_time = time.perf_counter()

result = unknown_signature(lst)

end_time = time.perf_counter()
execution_time_python = end_time - start_time

print("Result:", result)
print(f"Execution time: {execution_time_python:.10f} seconds")

Result: 3.0
Execution time: 0.0001790000 seconds


In [98]:
def unknown_signature_numpy(lst):
    return np.mean(lst)

lst = np.array([1, 2, 3, 4, 5])

start_time_np = time.perf_counter()

result_np = unknown_signature_numpy(lst)

end_time_np = time.perf_counter()
execution_time_numpy = end_time_np - start_time_np

print("Result:", result_np)
print(f"Execution time: {execution_time_numpy:.10f} seconds")

Result: 3.0
Execution time: 0.0001613000 seconds


## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [99]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [100]:
def unknown_signature_numpy(lst_np, mask, new_value):
    mask_np = np.array(mask)
    lst_np[mask_np] = new_value
    return lst_np.tolist()

lst_np = np.array([1, 2, 3, 4, 5])
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst_np, mask, new_value)
lst

[0, 2, 0, 4, 0]

### Task 7.2

In [105]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [106]:
def unknown_signature_numpy(list1_np, list2_np):
    
    bitwise_complement = ~list1_np
    bitwise_and = np.bitwise_and(list1_np, list2_np)
    bitwise_or = np.bitwise_or(list1_np, list2_np)
    
    return bitwise_complement.tolist(), bitwise_and.tolist(), bitwise_or.tolist()

list1_np = np.array([5, 2, 7, 4, 9])
list2_np = np.array([3, 6, 1, 8, 10])
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature_numpy(list1_np, list2_np)

result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

### Task 7.3 Optional

In [34]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [35]:
# write your numpy code here